add_rules("mode.debug", "mode.release")
add_requires("gtest")

target("base_test")
    set_kind("binary")
    add_includedirs("include")
    add_files("test/base_test.cpp")
    add_files("src/base.c")
    add_packages("gtest")

target("processor_API_test")
    set_kind("binary")
    add_includedirs("include")
    add_files("test/processor_API_test.cpp")
    add_files("src/processor.c")
    add_files("src/base.c")
    add_files("src/object_utils.c")
    add_files("src/player_dash.c")
    add_files("src/units/*.c")
    add_packages("gtest")

target("graphic_demo")
    add_rules("qt.widgetapp")
    add_headerfiles("include/qt/qt_graphic_drive.h")
    add_headerfiles("include/draw.h")
    add_files("test/qt_graphic_test.cpp")
    add_files("src/qt_draw.cpp")

