

void init_Timer(){
    Xil_Out32(
        XPAR_TMRCTR_0_BASEADDR + XTC_TCSR_OFFSET,
        Xil_In32(XPAR_TMRCTR_0_BASEADDR + XTC_TCSR_OFFSET) & (~XTC_CSR_ENABLE_TMR_MASK)
    );

    Xil_Out32(
        XPAR_TMRCTR_0_BASEADDR + XTC_TLR_OFFSET,
        TIMER0_RESET_VALUE
    ); 

    Xil_Out32(
        XPAR_TMRCTR_0_BASEADDR + XTC_TCSR_OFFSET,
        Xil_In32(XPAR_TMRCTR_0_BASEADDR + XTC_TCSR_OFFSET) | XTC_CSR_LOAD_MASK
    );

    Xil_Out32(
        XPAR_TMRCTR_0_BASEADDR + XTC_TCSR_OFFSET,
        Xil_In32(XPAR_TMRCTR_0_BASEADDR + XTC_TCSR_OFFSET) | (
            XTC_CSR_ENABLE_TMR_MASK | 
            XTC_CSR_DOWN_COUNT_MASK | (
                XTC_CSR_AUTO_RELOAD_MASK & 
                ~XTC_CSR_LOAD_MASK
            )
        )
    );

    Xil_Out32(
        XPAR_TMRCTR_0_BASEADDR + XTC_TCSR_OFFSET,
        Xil_In32(XPAR_TMRCTR_0_BASEADDR + XTC_TCSR_OFFSET) | 
        XTC_CSR_INT_OCCURED_MASK | 
        XTC_CSR_ENABLE_INT_MASK
    ); 
}